name: Automate Data Preprocessing

# Trigger: Jalan setiap kali ada push ke branch main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  preprocess-job:
    runs-on: ubuntu-latest

    steps:
    # Mengambil kode dari repository 
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Menyiapkan Python 3.12 
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # Install library dari requirements.txt
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Menjalankan Script Automate 
    - name: Run Preprocessing Script
      run: python preprocessing/automate_Tiksnapsr.py

    # Menyimpan hasil output sebagai 'Artifact'
    - name: Upload Processed Data
      uses: actions/upload-artifact@v4
      with:
        name: cleaned-dataset
        path: preprocessing/water_potability_preprocessing/*.csv
        retention-days: 5